name: cpc3
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - cudatoolkit=10.2
  - cython
  - nose
  - numpy>=1.20
  - pip
  - psutil
  - pysoundfile
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - tqdm
  - joblib
  - openblas-devel
  - librosa
  - pandas=1.2.4
  - pip:
    - progressbar2
    - matplotlib
    - sox
    - threadpoolctl==3.1.0
    - torch-audiomentations
